[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
lettre = { version = "0.11", features = ["smtp-transport", "builder"] }
chrono = { version = "0.4.41", features = ["serde"] }
dotenv = { version = "0.15" }
lazy_static = "1.5.0"
